<template>
  <div class="home-page">
    <a-button type="primary">xin chao
      <a-icon type="setting"></a-icon>
    </a-button>
    Lorem ipsum dolor sit amet.
    Ad corporis tempora amet nobis?
    Reprehenderit consequuntur sunt excepturi a.
    Maiores ratione voluptatem fugit vitae.
    Magni alias provident quo nihil?
    Voluptate magnam ab voluptates voluptatem!
    Quis, saepe. Minima, voluptate incidunt.
    Qui doloribus aspernatur rem praesentium.
    Ex iste facilis recusandae. Accusamus?
    Omnis repudiandae debitis eveniet ut!
    Eveniet voluptatum corrupti itaque consequuntur!
    Mollitia alias ab quibusdam quaerat.
    Fugiat corrupti mollitia quo praesentium?
    Ratione cumque fuga tenetur expedita.
    Nesciunt placeat fugit recusandae mollitia?
    Molestiae blanditiis illo aut doloremque?
    Maxime tenetur corrupti modi eveniet!
    Inventore id itaque beatae tempora.
    In, placeat. Consectetur, distinctio perspiciatis.
    Dolorum fugit libero voluptatum commodi!
    Cupiditate dolores consectetur mollitia temporibus.
    Consectetur nam atque illo nulla.
    Autem blanditiis error ea voluptatum.
    Repudiandae error amet fugiat pariatur?
    Eaque, velit. Eius, esse architecto!
    Nobis cum eius ipsum vel!
    Adipisci explicabo sit doloremque libero?
    Consequatur quae quasi expedita dolor.
    Molestias commodi temporibus saepe officiis!
    Cum tempore non explicabo similique.
    Officia in nam asperiores sit!
    Molestiae nisi a explicabo at.
    Eius dolorum sunt voluptatum quis.
    Eveniet esse at impedit in!
    Voluptate fuga minus recusandae iusto.
    Quam recusandae sint voluptatum itaque.
    Eaque minus debitis assumenda non.
    Fuga deserunt voluptates iste sequi.
    Fuga aspernatur maiores atque facilis!
    Ab reiciendis excepturi itaque. Porro!
    Commodi facilis dicta numquam suscipit!
    Tenetur, eaque error. Fugiat, obcaecati!
    Minima molestiae culpa rem quasi.
    Suscipit possimus deserunt laboriosam aperiam?
    Voluptatum nesciunt laborum provident optio?
    Incidunt porro quis voluptate placeat.
    Nostrum illo qui exercitationem eveniet!
    Perferendis distinctio neque molestiae. Reiciendis.
    Facilis ipsa possimus alias ad!
    Tempore quis ipsa nam porro.
    Fugit sequi temporibus iusto cum?
    Architecto doloremque distinctio molestias quos?
    Cumque reiciendis quae temporibus voluptatem!
    In perspiciatis accusamus ratione ad!
    Eligendi assumenda labore explicabo harum!
    Minus eos dolores non eligendi.
    Sint placeat iure beatae perferendis?
    Itaque molestias in accusantium rerum.
    Quis pariatur facere accusamus. Consequuntur.
    Explicabo ut qui voluptatibus at.
    Voluptate aperiam omnis nulla magnam.
    Asperiores, debitis? Odit, explicabo eaque!
    Nulla maiores quo quas quaerat?
    Eum quisquam quidem culpa assumenda!
    Amet sed commodi obcaecati est.
    Placeat dolore modi quod ea?
    Sunt saepe culpa eligendi illo?
    Placeat maiores veniam dolorem aspernatur.
    Libero iusto obcaecati porro ut.
    Doloremque excepturi cupiditate impedit quas?
    Voluptatum impedit ducimus magni earum!
    Ea asperiores dolorum rem placeat!
    Autem pariatur impedit corporis nemo!
    Ipsa, deserunt obcaecati. Omnis, incidunt.
    Dolorum accusamus itaque facilis nihil!
    Minima consectetur minus eligendi numquam.
    Sed alias fuga nobis iure?
    Ea animi maxime accusamus molestias!
    Praesentium quibusdam repudiandae voluptatem atque?
    Repudiandae accusamus vero inventore nobis.
    Illo, nemo? At, iusto animi?
    Nisi sed blanditiis quia dolorum?
    Quia voluptatem distinctio esse sed?
    Quia quos tempora laborum molestias.
    Cupiditate repellendus natus reiciendis velit?
    Dolor dolore dicta voluptatibus quibusdam.
    Ab minima excepturi aliquid doloremque!
    Laborum doloremque laboriosam dignissimos debitis?
    At laboriosam id assumenda impedit!
    Deleniti, ea placeat. Id, suscipit?
    Beatae totam fugit facere dolore.
    Adipisci nisi perferendis natus eos!
    Unde labore expedita tempora quisquam.
    Numquam illum praesentium exercitationem itaque!
    Aliquid cum assumenda fugit nihil?
    Tempora delectus doloribus ducimus repellendus!
    Libero iste officiis eveniet cumque?
    Tempore similique eius qui odit?
    Odit est totam delectus repellat.
    Magnam eligendi consequuntur officia doloremque.
    Vel sapiente eligendi nesciunt minima?
    Expedita consectetur voluptate nulla tempore?
    Asperiores doloremque reprehenderit rem temporibus.
    Impedit, excepturi expedita! Eaque, qui.
    Dolor distinctio eos asperiores autem.
    Illo molestiae tempora impedit totam.
    Ab, dolore? Omnis, et quas.
    Velit tempora maxime autem natus.
    Laboriosam provident saepe voluptatibus autem!
    Cumque cum nostrum consequuntur similique?
    Sapiente nesciunt eos voluptate illo?
    Aperiam in consequatur asperiores error?
    Cum perspiciatis maxime pariatur doloribus.
    Doloribus modi quisquam aspernatur earum?
    Debitis eveniet voluptatem amet eum.
    Repellat ratione aut asperiores quo.
    Sunt illo explicabo laboriosam delectus!
    Commodi, aliquam laborum. Odit, earum!
    Doloribus vel iure voluptate illo.
    Molestiae quae ratione consectetur sapiente.
    Aliquam enim ea voluptates minima?
    Enim doloribus esse rem nemo?
    Ut perspiciatis voluptates fugit reiciendis!
    Ea, illo. Tenetur, illo consequatur!
    Iste qui voluptate voluptas esse.
    Sit ex tempore corrupti a?
    Maiores eveniet modi incidunt molestias.
    Quia quis aperiam obcaecati. Autem?
    Quos quam nihil quasi impedit.
    Necessitatibus laudantium voluptate eius alias.
    Officia repellendus obcaecati earum nam.
    Facere aspernatur ipsum omnis deleniti?
    Soluta accusamus fugiat sequi voluptate.
    Beatae quaerat cupiditate nulla corporis?
    Architecto iure molestiae magnam facere.
    Quidem repellat rem tempore odit.
    Quam minus quibusdam officiis iste?
    Consequuntur laudantium eos amet reprehenderit!
    Architecto corporis recusandae eveniet dolorum.
    Temporibus, animi! Mollitia, adipisci quibusdam!
    Fugit vitae modi labore repellat.
    Quis sequi porro perferendis ut.
    Delectus tempore voluptatibus nihil! Cupiditate!
    Officia optio accusamus ex inventore?
    Voluptate enim voluptatibus dolorem ratione.
    Assumenda veniam placeat quaerat ipsum.
    Illum labore esse iure consequatur?
    Veritatis ab cum culpa maxime.
    Expedita vitae culpa quia quidem!
    Asperiores earum amet hic molestias.
    Aut amet ipsam perspiciatis voluptatum!
    Facilis assumenda est pariatur a?
    Eius ipsam eum delectus minus!
    Deleniti dolore in molestiae debitis?
    Explicabo ab neque saepe eaque.
    Magni dicta omnis earum aliquid?
    Ut quidem sequi perspiciatis consequuntur.
    Ab sunt voluptas vero soluta.
    Quibusdam recusandae inventore eaque asperiores.
    Quibusdam distinctio ratione sapiente ipsa.
    Architecto temporibus totam odit culpa?
    Vero exercitationem modi dolore neque?
    Assumenda recusandae blanditiis quas cupiditate?
    Nemo suscipit obcaecati consectetur nam.
    Quae iste ipsam eum ex.
    Ullam aliquam tenetur a cumque?
    Voluptas accusantium consectetur laudantium numquam?
    Voluptas rem quod beatae quidem!
    Quam vel sit officiis quod?
    Quo temporibus quas doloribus doloremque.
    Eligendi nemo fugit optio harum.
    Reprehenderit deserunt tempora ab hic.
    Veritatis illo nesciunt aliquid rerum?
    Dicta omnis nostrum id aut.
    Voluptatibus error alias aliquid non.
    Ratione at animi doloremque vel?
    Adipisci repellat earum incidunt numquam!
    Qui voluptas ea recusandae dolore?
    Impedit fugit et at illum?
    Enim iure voluptas magnam nobis.
    Nisi veniam atque minus quia?
    Quod obcaecati qui explicabo distinctio.
    Beatae blanditiis maxime quaerat enim?
    Assumenda doloribus explicabo inventore impedit.
    Ullam, reiciendis? Enim, velit sapiente!
    Quam ipsum nemo id perspiciatis?
    Ad fugit modi praesentium nam.
    Unde modi incidunt excepturi rem.
    Voluptates tempore distinctio pariatur atque!
    Tempora a beatae illo quas!
    Illo itaque doloribus animi laborum?
    Debitis quas esse magni minus?
    Incidunt cum consectetur exercitationem illum?
    Ut eos illum impedit autem?
    Unde illo omnis suscipit iste.
    Cupiditate sunt et fuga odio!
    Nihil ut quam ipsam aperiam!
    Delectus ipsum rem autem iste?
    Eveniet consequatur molestias nesciunt ad.
    Mollitia similique voluptatum vero recusandae.
    Eaque ducimus deleniti animi omnis?
    Veniam hic facilis corrupti necessitatibus.
    Odit explicabo ex sapiente aliquid.
    Iusto et quis modi officiis.
    Numquam aliquid optio nam exercitationem!
    Doloribus maiores voluptates velit voluptatibus?
    Commodi obcaecati dicta consequuntur ex.
    Architecto ex eum blanditiis tempore.
    Qui expedita dolorem maiores temporibus!
    Pariatur, ab. Nam, deserunt blanditiis.
    Optio minima nisi qui ad.
    Facere minima ut beatae illo?
    Modi magni dolorem ad reiciendis.
    Exercitationem earum libero deserunt minima.
    Eveniet quis accusamus nam illum.
    Nulla dolorum iusto voluptatibus perferendis?
    Ad magni a quaerat voluptatum?
    Natus animi architecto modi similique.
    Saepe, cum. Necessitatibus, consectetur dignissimos.
    Tenetur deserunt explicabo quidem unde?
    Porro quisquam accusantium consequuntur facilis!
    Qui dolores earum ex quo!
    Minus fuga fugit nostrum aperiam.
    Ut, laudantium dolorem. Aliquid, obcaecati!
    Quos eligendi praesentium nam quaerat?
    Error fuga architecto suscipit temporibus.
    Labore corrupti ex autem praesentium?
    Reiciendis suscipit omnis eos error!
    Error pariatur repudiandae dicta iure.
    Blanditiis quo placeat quia soluta?
    At eius quo quis corporis?
    Doloremque magni laborum adipisci consectetur!
    Quos non suscipit et in?
    Adipisci voluptatem impedit eaque quod.
    Quibusdam quae modi impedit dignissimos.
    Ex culpa minus consequatur incidunt?
    Magnam alias enim maxime nihil.
    Animi magni enim voluptate tempora.
    Nobis, aperiam? Officiis, quasi facere!
    Blanditiis soluta quia ratione porro.
    Quo minus veniam quos dignissimos?
    Sequi, ut eaque. Adipisci, quam.
    Porro non laboriosam quia incidunt!
    Voluptatum illo ea deleniti perspiciatis?
    Dolorum adipisci saepe quibusdam vel.
    Voluptatum maiores alias fuga tenetur.
    Doloremque autem aspernatur fugiat assumenda.
    Laudantium similique delectus minus ipsam.
    Error nulla laborum ab inventore?
    Tempore deserunt provident assumenda perferendis.
    Nesciunt ad ut repudiandae quod.
    Quidem delectus neque eum assumenda.
    Cumque eaque a blanditiis nostrum.
    Doloremque quaerat quas enim minus!
    Fugit velit sequi esse tenetur!
    Voluptatem dicta quaerat iste sequi.
    Culpa doloribus eligendi blanditiis perspiciatis?
    Nemo autem nulla rerum et.
    Velit aliquid unde dolores eius!
    Facilis cum nihil natus amet?
    Architecto aut dolorem aliquam. Cupiditate!
    Reiciendis cum ea incidunt odit!
    Omnis pariatur in fugit impedit.
    Dolores reprehenderit odio provident eius.
    Modi dolorum vero aspernatur? Ipsa.
    Saepe iusto fugiat impedit dicta!
    Incidunt, ratione? Veniam, quae mollitia?
    Laboriosam nesciunt vel illo ex!
    Distinctio tenetur et consequuntur temporibus!
    Quibusdam dolorem repellendus dolorum hic?
    Ipsum totam beatae officia ut.
    Deleniti est tempora delectus perspiciatis!
    Aliquam sequi maxime natus sapiente?
    Possimus recusandae rerum quos quis?
    Et ipsum similique consectetur fugit.
    Consequuntur culpa omnis mollitia atque.
    Maxime ipsam id consequatur molestias!
    Inventore harum rerum incidunt eligendi?
    Quas similique laboriosam optio pariatur?
    Quia aspernatur odio rem maiores!
    Ex ab at rem nulla!
    Amet beatae tempore possimus nihil!
    Voluptatum est ab quas sed.
    Incidunt vel laborum ex dolor!
    Magnam quidem at voluptatum nulla?
    Pariatur ipsum facere autem tempore!
    Cupiditate culpa autem soluta deleniti.
    Molestiae possimus nihil impedit maxime?
    At vero temporibus ullam quo.
    Alias, expedita eaque? Nihil, dolorem!
    Quidem unde veritatis nobis provident.
    Nisi vero harum sapiente libero!
    Alias consequatur officia quas omnis.
    Saepe sint delectus similique laborum.
    Suscipit aut cupiditate quos fugiat!
    Libero vel tempora natus tenetur.
    Velit fugit iste eligendi eaque.
    Optio ducimus veniam praesentium dicta.
    Fugiat nulla ullam delectus maxime?
    Et dignissimos rerum suscipit repudiandae.
    Alias ipsa et sunt excepturi.
    Culpa numquam officiis iusto aliquid.
    Ipsum voluptates sequi tenetur iste?
    Quos quas at animi laudantium!
    Inventore vel quidem ex cupiditate.
    Autem, eveniet iusto? Dicta, ea.
    Architecto numquam delectus voluptas natus.
    Delectus est pariatur necessitatibus possimus!
    Obcaecati eius rerum sed reprehenderit.
    Iusto quod iure velit ea.
    Similique impedit perferendis corrupti cupiditate.
    Harum est eligendi officia vitae?
    Nostrum quo ullam dolorem natus?
    Voluptatibus sit delectus eveniet commodi.
    Reiciendis eaque officiis dolorum facilis.
    Reiciendis iusto vitae doloribus nihil!
    At voluptatem praesentium exercitationem quam.
    Assumenda cumque obcaecati quos. Laudantium.
    Maiores at voluptas eum qui.
    Accusamus repellendus blanditiis exercitationem minima.
    Neque ipsum magni ab sint.
    Impedit nostrum ex modi sit.
    Asperiores animi enim illo temporibus.
    Laudantium modi eveniet molestiae animi?
    Blanditiis perferendis excepturi dolore iste.
    Saepe officiis aspernatur odit praesentium!
    Expedita ipsum nam unde ipsam.
    Odit aliquam voluptatum exercitationem laborum?
    Nostrum odio impedit modi facilis!
    Distinctio labore a aliquid ullam.
    Labore voluptas nisi harum quo.
    Quasi nobis ut quaerat doloremque?
    Dolorem consequatur quaerat temporibus itaque?
    Fuga alias ullam numquam rem.
    Omnis error odit minus voluptate.
    Fuga maiores alias necessitatibus aperiam?
    Fugiat culpa explicabo delectus veniam.
    Architecto asperiores repudiandae saepe quas!
    Sint amet quis laudantium nesciunt?
    Saepe harum enim doloribus modi.
    Autem repellendus voluptatibus velit quaerat.
    Ratione sint id modi ut.
    Aliquam velit ab mollitia doloremque!
    Minus dolorum enim cupiditate accusamus.
    Molestias ex doloremque perspiciatis modi.
    Laudantium fuga odit et reprehenderit.
    Omnis consectetur eligendi culpa atque.
    Minima ut illum iste perspiciatis?
    Quam animi esse perferendis ipsa.
    Reprehenderit molestiae vero quod consequuntur?
    Recusandae placeat porro odio obcaecati.
    Adipisci harum aliquam assumenda totam?
    Veritatis, accusamus! Tenetur, enim perspiciatis?
    Dicta alias aspernatur reiciendis praesentium.
    Exercitationem quisquam magnam deserunt officia.
    Libero sit praesentium corrupti perspiciatis.
    Laboriosam hic et porro aut?
    Molestias magnam architecto inventore similique!
    Perspiciatis sequi laboriosam quo deleniti?
    Maxime aliquid fugiat aperiam minus.
    Dolorem suscipit optio nulla iure.
    Incidunt consectetur in earum assumenda.
    Suscipit cum quisquam adipisci error!
    Architecto libero quibusdam vel porro!
    Laborum et commodi eos quas.
    Corporis fugit ratione voluptas quo.
    Suscipit, est! Reprehenderit, porro tempora.
    Recusandae consequuntur suscipit totam voluptatibus.
    Delectus molestiae quod quae consequatur.
    Reiciendis distinctio odio sint architecto!
    Cum fugit eligendi nisi minus!
    Quam atque voluptatibus nemo placeat?
    Iusto libero ex repudiandae numquam?
    Enim magnam voluptate eos perspiciatis?
    Deleniti voluptas cupiditate nostrum id?
    Architecto, quia. Iure, nemo quaerat.
    Amet voluptatem reprehenderit deleniti? In.
    Ipsum optio eius labore perspiciatis.
    Culpa mollitia officia eligendi suscipit.
    Voluptatem recusandae enim rem doloribus.
    Architecto ab necessitatibus doloribus maiores.
    Dolorem consequuntur laborum modi in?
    Exercitationem cumque necessitatibus optio reprehenderit?
    Impedit quia sed tempora dolor.
    Non necessitatibus ducimus recusandae praesentium!
    Quod saepe aut debitis exercitationem?
    Et eveniet repudiandae consectetur atque?
    Iste consequuntur inventore laborum eos?
    Autem libero iste soluta vel.
    Omnis temporibus in laborum tempore!
    Unde sapiente possimus iusto pariatur?
    Magnam ipsa nemo quod ea.
    Quam illum aliquam nemo reprehenderit.
    Soluta eos recusandae eveniet ullam?
    Necessitatibus modi officia animi esse?
    Libero voluptatem modi magni totam?
    Doloremque provident harum minus deserunt!
    Repellat corrupti consequatur voluptatum tempore?
    Sed dolorum nihil vero temporibus?
    Non amet impedit tempore sed?
    Ipsa exercitationem blanditiis praesentium aliquam?
    Quasi iure expedita iusto perferendis?
    Modi debitis rerum minima quod.
    Voluptatum incidunt laboriosam quibusdam magni!
    Voluptate nam velit mollitia beatae.
    Minima provident cum molestiae pariatur.
    Modi nam impedit tempora molestias.
    Neque eius a possimus earum.
    Doloremque repudiandae aut ex veritatis!
    Neque voluptatibus sunt esse nulla?
    Dolore libero debitis repellat sunt.
    Est fugit corrupti cumque amet?
    Commodi non iusto tenetur ratione.
    Pariatur officia nam possimus fugiat?
    Nesciunt iusto animi officia sunt.
    Aspernatur fuga quisquam tempora unde?
    Ad nesciunt aspernatur dicta quod?
    Adipisci nemo unde fugit itaque!
    Voluptas laudantium suscipit odit delectus?
    Consectetur velit eum et quam!
    Perferendis, provident fugit! Natus, id.
    Perferendis culpa vitae corporis molestias.
    Delectus praesentium corporis tempore dolores?
    Neque perspiciatis accusamus ducimus rem!
    Eos nam aut nobis perferendis.
    Eaque atque nisi nihil ducimus.
    A illum officiis earum quo.
    Doloribus aliquid magni soluta necessitatibus.
    Fuga quibusdam magnam incidunt omnis.
    Dolor beatae animi alias quo.
    Dicta commodi temporibus perspiciatis nulla?
    Ducimus pariatur quam doloribus error!
    Corporis quod consectetur sint possimus.
    Necessitatibus commodi veniam amet enim.
    Dolor et unde quas suscipit?
    Nulla voluptatem obcaecati reiciendis vero?
    Commodi quis totam deleniti animi.
    Natus ducimus nisi sed? Illum!
    Ipsam architecto excepturi ab adipisci?
    Doloremque aliquam numquam minus voluptatibus.
    At animi eum commodi vitae.
    Dolores magnam in explicabo molestiae.
    Enim tenetur culpa ad voluptate.
    Voluptas ullam temporibus cumque debitis!
    Aperiam eius cum blanditiis eveniet.
    Ratione corrupti aspernatur ea expedita.
    Consequuntur quo eum odit asperiores!
    Minima saepe corrupti quaerat officiis!
    Deleniti ducimus illum tenetur et.
    Reiciendis dolorem autem sed perferendis!
    Repudiandae voluptate sunt molestias placeat!
    Temporibus quia repellendus facere expedita.
    Repellendus sed dicta officiis corporis?
    Maxime nulla deleniti fuga tenetur.
    Voluptate eligendi aliquam quod provident?
    Eaque dolor nesciunt at alias?
    In quibusdam unde sed eum?
    Ea facere veniam voluptas earum.
    Nam suscipit ipsam cupiditate quidem?
    Eaque exercitationem odit voluptas omnis.
    Animi eum qui impedit quidem.
    Ab, exercitationem. Molestiae, magnam tenetur?
    Possimus, tenetur. Rerum, voluptatem nobis.
    Ad magnam minima autem aliquam.
    Mollitia delectus tempore repellat eos?
    Cumque explicabo omnis doloremque ipsum?
    Repellendus quo natus voluptatem labore.
    Voluptatem eos omnis inventore assumenda!
    Saepe ipsa nulla dicta dolores!
    Sequi quos doloribus accusamus molestiae?
    Reiciendis doloribus rerum quidem est.
    Autem excepturi temporibus exercitationem esse!
    Quos dicta magni optio facere.
    Omnis iste odit aliquam? Deleniti.
    Voluptatem impedit ex fugiat deserunt?
    Provident porro explicabo cupiditate possimus!
    Quod ut hic magnam ipsum.
    Accusamus voluptate corporis in veritatis.
    Laudantium quia corporis similique quisquam?
    Excepturi qui debitis porro veritatis!
    Libero consequatur consequuntur quis officiis.
    Omnis corporis amet in odio?
    Est deserunt aliquid debitis tempora.
    Voluptatem neque aliquid pariatur aliquam!
    Maxime aliquam dignissimos autem tempora!
    Laboriosam distinctio tempora veniam eum?
    Eum nobis sunt adipisci voluptas!
    Autem deleniti debitis perspiciatis quasi.
    Optio voluptatibus inventore sequi veritatis!
    Minima, repellat natus! Natus, dolore?
    Cupiditate quod nulla culpa blanditiis?
    Veritatis quo doloribus ipsum deleniti.
    Fugiat deserunt corrupti molestias necessitatibus.
    Sed molestias sequi veritatis minus.
    Maxime, sed sint. Repudiandae, dolore.
    Nemo eos deleniti iusto veniam.
    Dignissimos nesciunt modi quis? Libero?
    Saepe quisquam sint ex officia!
    Rem reprehenderit officiis ex earum.
    Reprehenderit officia at dignissimos quisquam?
  </div>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
//
});
</script>

<style lang="scss">

</style>
